const config=window.DICE_CONFIG;
const rotations=['rotateX(-17deg) rotateY(0deg)','rotateX(-17deg) rotateY(-90deg)','rotateX(-17deg) rotateY(90deg)','rotateX(-107deg) rotateY(0deg)','rotateX(-17deg) rotateY(180deg)','rotateX(73deg) rotateY(0deg)'];
const cube=document.querySelector('#cube'),rollButton=document.querySelector('#rollButton'),grid=document.querySelector('#cardsGrid'),result=document.querySelector('#result'),resultImage=document.querySelector('#resultImage'),resultTitle=document.querySelector('#resultTitle'),resultText=document.querySelector('#resultText');
let current=0;const flipped=new Set();
function renderCards(){grid.innerHTML=config.faces.map((face,i)=>`<button class="card ${i===current?'active':''} ${flipped.has(i)?'flipped':''}" data-index="${i}" type="button" aria-pressed="${flipped.has(i)}"><span class="card-inner"><span class="card-face card-front"><span class="card-image"><img src="${face.image}" alt="${face.title}" loading="lazy"></span><span class="card-copy"><span class="number">0${i+1}</span><h3>${face.title}</h3><p>${face.short}</p></span><span class="flip"><span>Ver reto</span><b>↻</b></span></span><span class="card-face card-back"><span><span class="number">TU ACCIÓN</span><h3>${face.title}</h3><p>${face.message}</p></span><span class="flip"><span>Volver</span><b>↺</b></span></span></span></button>`).join('');grid.querySelectorAll('.card').forEach(card=>card.addEventListener('click',()=>toggleCard(Number(card.dataset.index))))}
function showFace(i){current=i;cube.style.transform=rotations[i];result.classList.add('changing');setTimeout(()=>{const face=config.faces[i];resultImage.src=face.image;resultImage.alt=face.title;resultTitle.textContent=face.title;resultText.textContent=face.message;result.classList.remove('changing')},170);renderCards()}
function toggleCard(i){flipped.has(i)?flipped.delete(i):flipped.add(i);showFace(i)}
function roll(){rollButton.disabled=true;const next=Math.floor(Math.random()*6),x=720+Math.floor(Math.random()*3)*360,y=720+Math.floor(Math.random()*3)*360;cube.style.transform=`rotateX(${x}deg) rotateY(${y}deg)`;setTimeout(()=>{showFace(next);rollButton.disabled=false},1050)}
rollButton.addEventListener('click',roll);renderCards();
